# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 13:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jirani', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('business_description', models.TextField(max_length=80)),
                ('business_number', models.IntegerField(default=0)),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='jirani.Hood')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
